name: localization_manager_plugin
description: Library for creating plugins for [Localization Manager](https://github.com/necodeIT/localization-manager).
version: 0.0.1
homepage: https://github.com/necodeIT/localization_manager_plugin
environment:
  sdk: ">=2.18.2 <3.0.0"

dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  uuid: ^3.0.7
